### ISSUE TITLE
Not auto-switching after a long period 

### ISSUE THREAD

**Issue by 0sm3l** [autominer/autominer#8]
I've noticed that when I leave the program running overnight the messages about profitability do not show up in the morning and it gets stuck mining on one algorithm.  When restarted it works fine again for a couple of hours. . Is there any way to look at the code and maybe collaborate?

**Comment by synchroph** [comment]
For me the second day is working fine. I just set priority above normal for autominer.exe and update_interval: 45.

**Comment by 0sm3l** [comment]
I noticed it was only one of my miners. Switched to another program and now it's all good.
